from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import sys
import base64
import tempfile
import subprocess
import threading
import io
import time
from PIL import Image, ImageDraw  # 🌟 រៀបចំ Import ឱ្យមានរបៀប (Compression + Mock Text)

app = Flask(__name__)
CORS(app) 

OS_TYPE = sys.platform

# ==========================================
# 📂 មុខងារលោតផ្ទាំងរើស Folder
# ==========================================
selected_folder_path = ""

def open_folder_dialog_windows():
    global selected_folder_path
    import tkinter as tk
    from tkinter import filedialog
    root = tk.Tk()
    root.withdraw()
    root.attributes('-topmost', True)
    selected_folder_path = filedialog.askdirectory(title="ជ្រើសរើសទីតាំងរក្សាទុកឯកសារស្កេន")
    root.destroy()

@app.route('/choose_folder', methods=['GET'])
def choose_folder():
    global selected_folder_path
    selected_folder_path = ""
    
    if OS_TYPE == 'darwin':
        script = 'tell application "System Events" to activate\ntell application "System Events" to return POSIX path of (choose folder with prompt "ជ្រើសរើសទីតាំងរក្សាទុកឯកសារស្កេន")'
        try:
            result = subprocess.run(['osascript', '-e', script], capture_output=True, text=True)
            if result.returncode == 0:
                selected_folder_path = result.stdout.strip()
        except Exception as e:
            return jsonify({'status': 'error', 'message': str(e)})
    else:
        t = threading.Thread(target=open_folder_dialog_windows)
        t.start()
        t.join()
    
    if selected_folder_path:
        return jsonify({'status': 'success', 'path': os.path.normpath(selected_folder_path)})
    else:
        return jsonify({'status': 'error', 'message': 'បោះបង់ការជ្រើសរើស'})


# ==========================================
# 🖨️ ១. មុខងារស្កេនទាញយករូប (មានភ្ជាប់មុខងារ Test Mode កម្រិតខ្ពស់)
# ==========================================
@app.route('/scan', methods=['POST'])
def scan_document():
    data = request.json
    app_no = data.get('application_no', 'Unknown')
    temp_dir = tempfile.gettempdir()
    # 🌟 ប្រើពេលវេលាជាក់ស្តែង ដើម្បីកុំឱ្យជាន់ឈ្មោះ File ចាស់ ពេលស្កេនជាប់ៗគ្នា
    temp_path = os.path.join(temp_dir, f"temp_eps_scan_{int(time.time())}.jpg")

    scan_success = False
    error_msg = ""

    try:
        # ១. ព្យាយាមស្កេនពីម៉ាស៊ីនពិតប្រាកដសិន
        if OS_TYPE == 'win32':
            try:
                import pythoncom # type: ignore
                import win32com.client # type: ignore
                pythoncom.CoInitialize()      
                devManager = win32com.client.Dispatch("WIA.DeviceManager")
                scanner = None
                for info in devManager.DeviceInfos:
                    if info.Type == 1:
                        scanner = info.Connect()
                        break
                if scanner:
                    item = scanner.Items[1]
                    image = item.Transfer("{B96B3CAE-0728-11D3-9D7B-0000F81EF32E}") 
                    image.SaveFile(temp_path)
                    scan_success = True
                else:
                    error_msg = "រកមិនឃើញម៉ាស៊ីនស្កេន Windows ទេ!"
                pythoncom.CoUninitialize()
            except Exception as e:
                error_msg = str(e)

        elif OS_TYPE == 'darwin':
            try: # 🌟 (ជួសជុល) ត្រូវតែមាន Try Except នៅទីនេះទើបវាអត់គាំងលើ Mac
                command = ['scanimage', '--format=jpeg', '--resolution', '300', '-o', temp_path]
                result = subprocess.run(command, capture_output=True, text=True)
                if result.returncode == 0:
                    scan_success = True
                else:
                    error_msg = result.stderr
            except Exception as e:
                error_msg = str(e)

        # 🌟 ២. (SIMULATION MODE) បើគ្មានម៉ាស៊ីនស្កេនទេ បង្កើតរូបភាពតេស្តដោយស្វ័យប្រវត្តិ
        if not scan_success:
            print(f"⚠️ កំពុងដំណើរការ MOCK MODE ដោយសារ៖ {error_msg}")
            # គូរក្រដាសពណ៌ស ទំហំ A4 (បញ្ឈរ)
            img = Image.new('RGB', (800, 1130), color='white')
            d = ImageDraw.Draw(img)
            # គូសប្រអប់ព័ទ្ធជុំវិញ
            d.rectangle([(20, 20), (780, 1110)], outline="#0d6efd", width=5)
            d.rectangle([(40, 40), (760, 1090)], outline="#6c757d", width=2)
            
            # សរសេរព័ត៌មានក្លែងបន្លំ (ដើម្បីឱ្យដឹងថាវាជារូបតេស្ត)
            d.text((100, 100), "=== TEST SCANNED DOCUMENT ===", fill="red")
            d.text((100, 150), f"CANDIDATE ID : {app_no}", fill="black")
            d.text((100, 200), f"SCAN TIME    : {time.ctime()}", fill="blue")
            d.text((100, 300), "This is a simulated document generated by Python", fill="gray")
            d.text((100, 320), "because no physical scanner was connected.", fill="gray")
            
            img.save(temp_path, format='JPEG', quality=90)

        # ៣. អានរូបភាពពី Temp File រួចបម្លែងជា Base64 បញ្ជូនទៅកាន់ Web
        with open(temp_path, "rb") as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
            base64_image = f"data:image/jpeg;base64,{encoded_string}"

        # លុបរូបបណ្តោះអាសន្នចោលវិញ
        if os.path.exists(temp_path):
            os.remove(temp_path)

        return jsonify({'status': 'success', 'image_base64': base64_image})

    except Exception as e:
        return jsonify({'status': 'error', 'message': f"System Error: {str(e)}"})


# ==========================================
# 💾 ២. មុខងាររក្សាទុករូបភាពជាផ្លូវការ (Save + Dynamic Compression)
# ==========================================
@app.route('/save', methods=['POST'])
def save_document():
    data = request.json
    app_no = data.get('application_no')
    save_dir = data.get('save_dir')
    base64_data = data.get('image_base64')
    
    # 🌟 DYNAMIC SIZE: ទទួលយកទំហំកំណត់ពី Web គិតជា KB (បើអត់បោះមក យក Default 1000 KB ស្មើ 1MB)
    max_size_kb = int(data.get('max_size_kb', 1000)) 
    
    if not app_no or not save_dir or not base64_data:
        return jsonify({'status': 'error', 'message': 'ទិន្នន័យមិនគ្រប់គ្រាន់សម្រាប់ការរក្សាទុក!'})
        
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
        
    filename = f"{app_no}.jpg"
    final_save_path = os.path.join(save_dir, filename)
    
    try:
        # កាត់ក្បាល "data:image/jpeg;base64," ចេញពីរូបភាព
        if "," in base64_data:
            base64_data = base64_data.split(",")[1]
            
        image_bytes = base64.b64decode(base64_data)
        image = Image.open(io.BytesIO(image_bytes))
        
        # បំប្លែងទៅជា RGB បើវាជា PNG/RGBA
        if image.mode != 'RGB':
            image = image.convert('RGB')

        # 🌟 ក្បួនដោះស្រាយបង្រួមទំហំឆ្លាតវៃ (Smart Compression Loop ថ្មី) 🌟
        quality = 100    # ចាប់ផ្តើមពីគុណភាពច្បាស់បំផុត ១០០%
        min_quality = 70 # ហាមបន្ថយគុណភាពអន់ជាង ៧០% ដាច់ខាត (ដើម្បីរក្សាភាពច្បាស់ Passport)
        step = 3         # បន្ថយម្តងបន្តិចៗ (៣%) ដើម្បីរក្សាគុណភាពឱ្យបានខ្ពស់បំផុត
        
        while True:
            img_byte_arr = io.BytesIO()
            # Save រូបចូល Memory សិន ដើម្បីឆែកទំហំ
            image.save(img_byte_arr, format='JPEG', quality=quality)
            size_kb = len(img_byte_arr.getvalue()) / 1024
            
            # បើទំហំតូចជាង ឬស្មើ 1000KB (1MB) ឬគុណភាពធ្លាក់ដល់កម្រិតកំណត់ហើយ
            if size_kb <= max_size_kb or quality <= min_quality:
                # សរសេរចូល Hard Disk ផ្លូវការ
                with open(final_save_path, 'wb') as f:
                    f.write(img_byte_arr.getvalue())
                break
            
            quality -= step # បន្តបន្ថយម្តង ៣% បើទំហំនៅតែធំជាង 1MB
            
        # ទាញយកទំហំ File ជាក់ស្តែងនៅលើកុំព្យូទ័រ
        final_size_kb = round(os.path.getsize(final_save_path) / 1024, 2)
        final_size_mb = round(final_size_kb / 1024, 2)
        
        return jsonify({
            'status': 'success', 
            'message': 'រក្សាទុកជោគជ័យ', 
            'file_path': final_save_path,
            'final_size': f"{final_size_mb} MB"
        })
        
    except Exception as e:
        return jsonify({'status': 'error', 'message': f"បញ្ហាក្នុងការរក្សាទុក៖ {str(e)}"})


if __name__ == '__main__':
    print("="*60)
    print(f"🚀 កម្មវិធី Local Bridge កំពុងដំណើរការលើប្រព័ន្ធ៖ {OS_TYPE.upper()}")
    print("🌐 Port ទំនាក់ទំនង៖ http://127.0.0.1:5005")
    print("="*60)
    
    is_threaded = False if OS_TYPE == 'darwin' else True
    app.run(host='127.0.0.1', port=5005, threaded=is_threaded)